[package]
name = "jjt"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image","mixer"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
debug=true